### ISSUE TITLE
Error with Zeek v4.1.1

### ISSUE THREAD

**Issue by keithjjones** [zeek/spicy-ldap#8]
https://github.com/zeek/spicy-ldap/blob/70b186e926a19501122fb7c616dc5008c195ac87/analyzer/main.zeek#L292

I'm running Zeek v4.1.1 and this error comes up:

```
logger: error in [REDACTED]/packages/spicy-ldap/main.zeek, line 292: identifier not defined: AllAnalyzers::Tag
logger: error in [REDACTED]/packages/spicy-ldap/main.zeek, line 292 and event.bif.zeek, line 406: use of undeclared alternate prototype (event(c:connection; atype:error; aid:count;) and protocol_confirmation)
```

**Comment by bbannier** [comment]
This was introduced by #7 and has since been rolled back. We still emit a deprecation warning for which cleanup is done in #10.
