### ISSUE TITLE
Environment variable in zkg.meta issues

### ISSUE THREAD

**Issue by keithjjones** [zeek/spicy-ldap#9]
https://github.com/zeek/spicy-ldap/blob/70b186e926a19501122fb7c616dc5008c195ac87/zkg.meta#L6

I also have this problem in my spicy analyzers and haven't figured out the right way around it.  This "SPICYZ" variable will cause issues, especially in later versions of Zeek.  Zeek v5, it's supposed to not be in there or it will throw an error.  For my application I cloned this repo and removed the env variable, but I'm flagging here so you know about it.  If you are able to find a good way to handle this, I am also interested for my spicy analyzers (openvpn, ipsec, etc).  I was just going to completely remove the env variable in my analyzers, but that will likely break it for some people.  Thanks!

**Comment by bbannier** [comment]
We now only look for spicyz in the zkg state dir if we cannot find it in `PATH`. That works with both zeek4 as well as zeek5 with a bundled spicyz.
